package ui;

import common.Validations;
import dao.ConnectionProvider;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.imageio.ImageIO;

/**
 *
 * @author HOME
 */
public class UpdateCredit extends javax.swing.JFrame {

    /**
     * Creates new form UpdateCredit
     */
    public UpdateCredit() {
        initComponents();
        setSize(850, 500);
        setLocationRelativeTo(null);
        txtCreditID.setEditable(false);
        txtClientName.setEditable(false);
        txtTotalCreditValue.setEditable(false);
        txtPendingBalance.setEditable(false);
        txtCreditDate.setEditable(false);
        txtCreditDeadline.setEditable(false);
        txtCreditState.setEditable(false);
        
        //establecer icono
        setImage();
    }
    
    //icono de la aplicación
    public void setImage() {
        try {
            InputStream imgStream = getClass().getResourceAsStream("/images/icono.png");
            if (imgStream != null) {
                setIconImage(ImageIO.read(imgStream));
            } else {
                System.out.println("Icono no encontrado");
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public void setCreditData(String creditID, String clientName, String totalCreditValue,
            String pendingBalance, String creditDate, String creditDeadline, String creditState) {
        txtCreditID.setText(creditID);
        txtClientName.setText(clientName);
        txtTotalCreditValue.setText(totalCreditValue);
        txtPendingBalance.setText(pendingBalance);
        txtCreditDate.setText(creditDate);
        txtCreditDeadline.setText(creditDeadline);
        txtCreditState.setText(creditState);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtCreditID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtClientName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTotalCreditValue = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPendingBalance = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCreditDate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCreditDeadline = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCreditState = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPaymentForCredit = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Actualizar Crédito");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 6, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 6, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 56, 850, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ID del Crédito");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 122, -1, -1));

        txtCreditID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCreditID.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtCreditID, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 143, 180, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Cliente");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 199, -1, -1));

        txtClientName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtClientName.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtClientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 220, 240, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Valor del crédito");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 277, -1, -1));

        txtTotalCreditValue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTotalCreditValue.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtTotalCreditValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 298, 240, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Valor pendiente");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 354, -1, -1));

        txtPendingBalance.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPendingBalance.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtPendingBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 375, 240, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Fecha del crédito");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 122, -1, -1));

        txtCreditDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCreditDate.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtCreditDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 143, 240, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Fecha límite de pago");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 199, -1, -1));

        txtCreditDeadline.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCreditDeadline.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtCreditDeadline, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 220, 240, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Estado del crédito");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 277, -1, -1));

        txtCreditState.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCreditState.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtCreditState, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 298, 240, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Valor del abono *");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 354, -1, -1));

        txtPaymentForCredit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPaymentForCredit.setForeground(new java.awt.Color(0, 0, 0));
        txtPaymentForCredit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPaymentForCreditKeyReleased(evt);
            }
        });
        getContentPane().add(txtPaymentForCredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 375, 240, -1));

        saveBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(0, 0, 0));
        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        saveBtn.setText("Guardar");
        saveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 404, 115, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whiteSmoke.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
        dispose();
    }//GEN-LAST:event_jLabel2MouseReleased

    private void txtPaymentForCreditKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaymentForCreditKeyReleased
        String payment = txtPaymentForCredit.getText().trim();

        if (!payment.matches(Validations.NUMBER_PATTERN)) {
            JOptionPane.showMessageDialog(null, "¡Debes ingresar el valor en números!", "Error de digitación",
                    JOptionPane.WARNING_MESSAGE);
            txtPaymentForCredit.setText("");
            return;
        }
    }//GEN-LAST:event_txtPaymentForCreditKeyReleased

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // botón guardar
        String creditID = txtCreditID.getText().trim();
        String paymentText = txtPaymentForCredit.getText().trim();
        String pendingBalanceText = txtPendingBalance.getText().trim();

        if (paymentText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un valor de pago.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        long paymentAmount;
        long pendingBalance;

        try {
            paymentAmount = Long.parseLong(paymentText);
            pendingBalance = Long.parseLong(pendingBalanceText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El valor ingresado no es un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (paymentAmount <= 0) {
            JOptionPane.showMessageDialog(null, "El valor de pago debe ser mayor a cero.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (paymentAmount > pendingBalance) {
            JOptionPane.showMessageDialog(null, "El valor de pago no puede ser mayor al saldo pendiente.", "Error", JOptionPane.ERROR_MESSAGE);
            txtPaymentForCredit.setText("");
            return;
        }

        long newPendingBalance = pendingBalance - paymentAmount;
        String newCreditState = (newPendingBalance == 0) ? "Pagado" : "Pendiente";

        // Consulta para actualizar saldo pendiente en clients_credits
        String updateCreditQuery = "UPDATE clients_credits SET pendingBalance = ?, creditState = ?, lastModified = CURRENT_TIMESTAMP WHERE clientsCredits_pk = ?";

        // Consulta para registrar el abono en credit_payments
        String insertPaymentQuery = "INSERT INTO credit_payments (clientsCredits_pk, paymentAmount) VALUES (?, ?)";

        try (Connection con = ConnectionProvider.getCon(); PreparedStatement pstUpdate = con.prepareStatement(updateCreditQuery); PreparedStatement pstInsert = con.prepareStatement(insertPaymentQuery)) {

            // Insertar el abono en credit_payments
            pstInsert.setString(1, creditID);
            pstInsert.setLong(2, paymentAmount);
            pstInsert.executeUpdate();

            // Actualizar el saldo pendiente en clients_credits
            pstUpdate.setLong(1, newPendingBalance);
            pstUpdate.setString(2, newCreditState);
            pstUpdate.setString(3, creditID);
            int updatedRows = pstUpdate.executeUpdate();

            if (updatedRows > 0) {
                JOptionPane.showMessageDialog(null, "Abono registrado y crédito actualizado correctamente.");
                dispose();
                new ViewCredits().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró el crédito para actualizar.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al registrar el abono: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateCredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateCredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateCredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateCredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateCredit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField txtClientName;
    private javax.swing.JTextField txtCreditDate;
    private javax.swing.JTextField txtCreditDeadline;
    private javax.swing.JTextField txtCreditID;
    private javax.swing.JTextField txtCreditState;
    private javax.swing.JTextField txtPaymentForCredit;
    private javax.swing.JTextField txtPendingBalance;
    private javax.swing.JTextField txtTotalCreditValue;
    // End of variables declaration//GEN-END:variables
}
